name: apotech
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dots_indicator: ^3.0.0  
  responsive_sizer: ^3.2.0
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.7.0
  pinput: ^3.0.1
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.9
  form_builder_validators: ^9.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    color: "#ffffff"

  android: true
  ios: true
